(in-package :cl-user)
(declaim (optimize (speed 1) (safety 3) (debug 1)))
(push :ci *features*)
(when (eq :linux (uiop:operating-system))
  (push (print (pathname (uiop:getenv "EXOTIC_DIR")))
        ql:*local-project-directories*))
(push #P"./" ql:*local-project-directories*)
(ql:quickload "py4cl2-cffi/config")
(setf py4cl2-cffi/config:*python-call-mode* :standard)
(asdf:load-system "py4cl2-cffi" :force t)
(ql:quickload "py4cl2-cffi-tests")
(py4cl2-cffi/config:print-configuration)
(let ((report (py4cl2-cffi-tests:run)))
  (when (or (plusp (slot-value report 'clunit::failed))
            (plusp (slot-value report 'clunit::errors)))
    (uiop:quit 1)))
(terpri)
(format t "!!STANDARD TESTS RAN SUCCESSFULLY!!")
(uiop:quit 0)
