(in-package :cl-user)
(push :travis *features*)
(push (print (pathname (uiop:getenv "EXOTIC_DIR")))
      ql:*local-project-directories*)
(push #P"~/" ql:*local-project-directories*)
(ql:quickload "py4cl2-cffi-tests")
(py4cl2-cffi/config:print-configuration)
(let ((report (py4cl2-cffi-tests:run)))
  (princ report)
  (when (or (plusp (slot-value report 'clunit::failed))
            (plusp (slot-value report 'clunit::errors)))
    (uiop:quit 1)))
(format t "!!ALL TESTS RAN SUCCESSFULLY!!")
(uiop:quit 0)
