;;; This file was automatically generated by gen.lisp in the same directory.
;;; Please do not edit this file manually.

(in-package :py4cl2-cffi/single-threaded)

(defun py4cl2-cffi/single-threaded:pyref
       (py4cl2-cffi::object &rest py4cl2-cffi::indices)
  (apply/single-threaded
   (lambda (&rest args3)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyref args3)))
   py4cl2-cffi::object py4cl2-cffi::indices))

(defun (setf py4cl2-cffi/single-threaded:pyref)
       (py4cl2-cffi::new-value py4cl2-cffi::object &rest py4cl2-cffi::indices)
  (apply/single-threaded
   (lambda (&rest args3)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyref args3)
       (apply #'(setf py4cl2-cffi:pyref) args3)))
   py4cl2-cffi::new-value py4cl2-cffi::object py4cl2-cffi::indices))

(defun py4cl2-cffi/single-threaded:import-function
       (py4cl2-cffi::name py4cl2-cffi::from &key (iterate:as nil))
  (funcall/single-threaded
   (lambda (&rest args4)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:import-function args4)))
   py4cl2-cffi::name py4cl2-cffi::from :as iterate:as))

nil

(defun py4cl2-cffi/single-threaded:python-start-if-not-alive ()
  (funcall/single-threaded
   (lambda (&rest args7)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:python-start-if-not-alive args7)))))

nil

(defun py4cl2-cffi/single-threaded:raw-pyeval (&rest py4cl2-cffi::code-strings)
  (apply/single-threaded
   (lambda (&rest args9)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:raw-pyeval args9)))
   py4cl2-cffi::code-strings))

nil

(defun py4cl2-cffi/single-threaded:import-module
       (py4cl2-cffi::name &key (iterate:as nil))
  (funcall/single-threaded
   (lambda (&rest args12)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:import-module args12)))
   py4cl2-cffi::name :as iterate:as))

nil

(defun py4cl2-cffi/single-threaded:pygenerator
       (function py4cl2-cffi::stop-value)
  (funcall/single-threaded
   (lambda (&rest args15)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pygenerator args15)))
   function py4cl2-cffi::stop-value))

nil

(defmacro py4cl2-cffi/single-threaded:defpyfun
          (py4cl2-cffi::fun-name
           &optional py4cl2-cffi::pymodule-name
           &key (iterate:as py4cl2-cffi::fun-name) (py4cl2-cffi::cache t)
           (py4cl2-cffi::lisp-fun-name (py4cl2-cffi::lispify-name iterate:as))
           (py4cl2-cffi::lisp-package *package*) (safety t))
  (funcall/single-threaded
   (lambda (&rest args16)
     (float-features:with-float-traps-masked t
       (funcall (macro-function 'py4cl2-cffi:defpyfun)
                (list* 'py4cl2-cffi:defpyfun args16) nil)))
   py4cl2-cffi::fun-name py4cl2-cffi::pymodule-name :as iterate:as :cache
   py4cl2-cffi::cache :lisp-fun-name py4cl2-cffi::lisp-fun-name :lisp-package
   py4cl2-cffi::lisp-package :safety safety))

nil

(defun py4cl2-cffi/single-threaded:export-function
       (function py4cl2-cffi::python-name)
  (funcall/single-threaded
   (lambda (&rest args17)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:export-function args17)))
   function py4cl2-cffi::python-name))

nil

(defun py4cl2-cffi/single-threaded:pyslot-value
       (py4cl2-cffi::object py4cl2-cffi::slot-name)
  (funcall/single-threaded
   (lambda (&rest args18)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyslot-value args18)))
   py4cl2-cffi::object py4cl2-cffi::slot-name))

(defun (setf py4cl2-cffi/single-threaded:pyslot-value)
       (py4cl2-cffi::new-value py4cl2-cffi::object py4cl2-cffi::slot-name)
  (funcall/single-threaded
   (lambda (&rest args18)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyslot-value args18)
       (apply #'(setf py4cl2-cffi:pyslot-value) args18)))
   py4cl2-cffi::new-value py4cl2-cffi::object py4cl2-cffi::slot-name))

(defun py4cl2-cffi/single-threaded:pyversion-info ()
  (funcall/single-threaded
   (lambda (&rest args21)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyversion-info args21)))))

nil

(defun py4cl2-cffi/single-threaded:raw-pyexec (&rest py4cl2-cffi::code-strings)
  (apply/single-threaded
   (lambda (&rest args22)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:raw-pyexec args22)))
   py4cl2-cffi::code-strings))

nil

(defun py4cl2-cffi/single-threaded:pyeval (&rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args24)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyeval args24)))
   py4cl2-cffi::args))

(defun (setf py4cl2-cffi/single-threaded:pyeval)
       (py4cl2-cffi::value &rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args24)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyeval args24)
       (apply #'(setf py4cl2-cffi:pyeval) args24)))
   py4cl2-cffi::value py4cl2-cffi::args))

(defun py4cl2-cffi/single-threaded:python-setattr
       (py4cl2-cffi::object py4cl2-cffi::slot-name py4cl2-cffi::value)
  (funcall/single-threaded
   (lambda (&rest args25)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:python-setattr args25)))
   py4cl2-cffi::object py4cl2-cffi::slot-name py4cl2-cffi::value))

nil

(defun py4cl2-cffi/single-threaded:pymethod-list
       (py4cl2-cffi::pyobject &key (py4cl2-cffi::as-vector nil))
  (funcall/single-threaded
   (lambda (&rest args27)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pymethod-list args27)))
   py4cl2-cffi::pyobject :as-vector py4cl2-cffi::as-vector))

nil

(defun py4cl2-cffi/single-threaded:pyslot-list
       (py4cl2-cffi::pyobject &key (py4cl2-cffi::as-vector nil))
  (funcall/single-threaded
   (lambda (&rest args29)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyslot-list args29)))
   py4cl2-cffi::pyobject :as-vector py4cl2-cffi::as-vector))

nil

(defun py4cl2-cffi/single-threaded:pystart ()
  (funcall/single-threaded
   (lambda (&rest args33)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pystart args33)))))

nil

(defun py4cl2-cffi/single-threaded:pymethod
       (py4cl2-cffi::object py4cl2-cffi::method-name &rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args35)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pymethod args35)))
   py4cl2-cffi::object py4cl2-cffi::method-name py4cl2-cffi::args))

nil

(defun py4cl2-cffi/single-threaded:python-getattr
       (py4cl2-cffi::object py4cl2-cffi::slot-name)
  (funcall/single-threaded
   (lambda (&rest args37)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:python-getattr args37)))
   py4cl2-cffi::object py4cl2-cffi::slot-name))

nil

(defun py4cl2-cffi/single-threaded:pyhelp
       (py4cl2-cffi::string-or-python-callable)
  (funcall/single-threaded
   (lambda (&rest args38)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyhelp args38)))
   py4cl2-cffi::string-or-python-callable))

nil

(defun py4cl2-cffi/single-threaded:python-alive-p ()
  (funcall/single-threaded
   (lambda (&rest args40)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:python-alive-p args40)))))

nil

(defmacro py4cl2-cffi/single-threaded:defpymodule
          (py4cl2-cffi::pymodule-name
           &optional (py4cl2-cffi::import-submodules nil)
           &key (py4cl2-cffi::cache t)
           (py4cl2-cffi::continue-ignoring-errors t)
           (py4cl2-cffi::lisp-package
            (py4cl2-cffi::lispify-name py4cl2-cffi::pymodule-name))
           (py4cl2-cffi::reload t) (py4cl2-cffi::recompile-on-change nil)
           (safety t) (py4cl2-cffi::silent py4cl2-cffi:*defpymodule-silent-p*))
  (funcall/single-threaded
   (lambda (&rest args42)
     (float-features:with-float-traps-masked t
       (funcall (macro-function 'py4cl2-cffi:defpymodule)
                (list* 'py4cl2-cffi:defpymodule args42) nil)))
   py4cl2-cffi::pymodule-name py4cl2-cffi::import-submodules :cache
   py4cl2-cffi::cache :continue-ignoring-errors
   py4cl2-cffi::continue-ignoring-errors :lisp-package
   py4cl2-cffi::lisp-package :reload py4cl2-cffi::reload :recompile-on-change
   py4cl2-cffi::recompile-on-change :safety safety :silent py4cl2-cffi::silent))

nil

(defun py4cl2-cffi/single-threaded:pyvalue
       (py4cl2-cffi::python-name-or-variable)
  (funcall/single-threaded
   (lambda (&rest args43)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyvalue args43)))
   py4cl2-cffi::python-name-or-variable))

(defun (setf py4cl2-cffi/single-threaded:pyvalue)
       (py4cl2-cffi::new-value py4cl2-cffi::python-name-or-variable)
  (funcall/single-threaded
   (lambda (&rest args43)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyvalue args43)
       (apply #'(setf py4cl2-cffi:pyvalue) args43)))
   py4cl2-cffi::new-value py4cl2-cffi::python-name-or-variable))

(defun py4cl2-cffi/single-threaded:pycall
       (py4cl2-cffi::python-callable &rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args45)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pycall args45)))
   py4cl2-cffi::python-callable py4cl2-cffi::args))

nil

(defun py4cl2-cffi/single-threaded:pystop ()
  (funcall/single-threaded
   (lambda (&rest args50)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pystop args50)))))

nil

(defun py4cl2-cffi/single-threaded:pyexec (&rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args52)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi:pyexec args52)))
   py4cl2-cffi::args))

nil

(defun py-module-pointer (py4cl2-cffi::name)
  (funcall/single-threaded
   (lambda (&rest args55)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::py-module-pointer args55)))
   py4cl2-cffi::name))

(defun (setf py-module-pointer) (py4cl2-cffi::module-pointer py4cl2-cffi::name)
  (funcall/single-threaded
   (lambda (&rest args55)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::py-module-pointer args55)
       (apply #'(setf py4cl2-cffi::py-module-pointer) args55)))
   py4cl2-cffi::module-pointer py4cl2-cffi::name))

(defun load-python-and-libraries ()
  (funcall/single-threaded
   (lambda (&rest args56)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::load-python-and-libraries args56)))))

nil

(defun pycall* (py4cl2-cffi::python-callable &rest py4cl2-cffi::args)
  (apply/single-threaded
   (lambda (&rest args58)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::pycall* args58)))
   py4cl2-cffi::python-callable py4cl2-cffi::args))

nil

(defun pyeval-save-thread ()
  (funcall/single-threaded
   (lambda (&rest args59)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::pyeval-save-thread args59)))))

nil

(defun pygil-held-p ()
  (funcall/single-threaded
   (lambda (&rest args60)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::pygil-held-p args60)))))

nil

(defun pyvalue* (py4cl2-cffi::python-value-or-variable)
  (funcall/single-threaded
   (lambda (&rest args61)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::pyvalue* args61)))
   py4cl2-cffi::python-value-or-variable))

(defun (setf pyvalue*)
       (py4cl2-cffi::new-value py4cl2-cffi::python-value-or-variable)
  (funcall/single-threaded
   (lambda (&rest args61)
     (float-features:with-float-traps-masked t
       (apply #'py4cl2-cffi::pyvalue* args61)
       (apply #'(setf py4cl2-cffi::pyvalue*) args61)))
   py4cl2-cffi::new-value py4cl2-cffi::python-value-or-variable))